services:
  # 1. Node.js (Next.js)
  flashtalk:
    image: minseong426/flashtalk:latest
    expose:
      - "3000"
    env_file:
      - .env
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m" 
        max-file: "3"

  # 2. Nginx 서비스
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - flashtalk
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m" 
        max-file: "3"